-- 안전하게 초기화 (FK 의존 무시)
SET FOREIGN_KEY_CHECKS = 0;

-- 2) 테이블 생성 (참조되는 테이블 먼저)
CREATE TABLE FACTORY (
  facId      INT NOT NULL,
  facName    VARCHAR(100) NOT NULL,
  created_at DATETIME DEFAULT NOW(),
  CONSTRAINT PK_FACTORY PRIMARY KEY (facId),
  CONSTRAINT UQ_FACTORY_NAME UNIQUE (facName)
);

CREATE TABLE ITEM (
  item_id    VARCHAR(36) NOT NULL,
  item_name  VARCHAR(100) NOT NULL,
  item_type  ENUM('FG','WIP','COMP') NOT NULL,
  unit       VARCHAR(10) DEFAULT 'EA',
  created_at DATETIME NULL,
  CONSTRAINT PK_ITEM PRIMARY KEY (item_id)
);

CREATE TABLE PRODUCT_MODEL (
  product_id  VARCHAR(36) NOT NULL,
  model_code  VARCHAR(50) NOT NULL,
  created_at  DATETIME NULL,
  CONSTRAINT PK_PRODUCT_MODEL PRIMARY KEY (product_id)
);

CREATE TABLE STATION (
  station_id    VARCHAR(36) NOT NULL,
  line_id       VARCHAR(36) NOT NULL,
  factory_id    INT NOT NULL,
  process_type  ENUM('PRESS','BODY','PAINT','ASSY') NOT NULL,
  line_name     VARCHAR(100),
  station_name  VARCHAR(100),
  station_type  VARCHAR(50),
  station       INT NOT NULL,
  created_at    DATETIME NULL,
  CONSTRAINT PK_STATION PRIMARY KEY (station_id)
);

CREATE TABLE WORK_ORDER (
  order_id   VARCHAR(36) NOT NULL,
  product_id VARCHAR(36) NOT NULL,
  qty_plan   INT NOT NULL,
  created_at DATETIME NULL,
  planned_s  DATETIME NULL,
  planned_e  DATETIME NULL,
  CONSTRAINT PK_WORK_ORDER PRIMARY KEY (order_id)
);

CREATE TABLE PRODUCT (
  p_id        VARCHAR(36) NOT NULL,
  order_id    VARCHAR(36) NULL,
  product_id  VARCHAR(36) NOT NULL,
  color_code  VARCHAR(50) NULL,
  created_at  DATETIME NULL,
  CONSTRAINT PK_PRODUCT PRIMARY KEY (p_id)
);

CREATE TABLE PRODUCT_ROUTING (
  routing_id   BIGINT NOT NULL AUTO_INCREMENT,
  line_id      VARCHAR(36) NOT NULL,
  product_id   VARCHAR(36) NOT NULL,
  process_seq  INT NOT NULL,
  process_type ENUM('PRESS','BODY','PAINT','ASSY') NOT NULL,
  duration     INT NULL,
  CONSTRAINT PK_PRODUCT_ROUTING PRIMARY KEY (routing_id),
  CONSTRAINT UQ_ROUTING UNIQUE (product_id, process_seq)
);

CREATE TABLE BOM (
  bom_id      BIGINT NOT NULL AUTO_INCREMENT,
  product_id  VARCHAR(36) NOT NULL,
  item_id     VARCHAR(36) NOT NULL,
  qty_per     DECIMAL(12,4) NOT NULL,
  CONSTRAINT PK_BOM PRIMARY KEY (bom_id)
);

CREATE TABLE STATION_EQUIPMENT (
  station_id   VARCHAR(36) NOT NULL,
  equipment_id VARCHAR(36) NOT NULL,
  installed_at DATETIME NOT NULL,
  CONSTRAINT PK_STATION_EQUIPMENT PRIMARY KEY (station_id, equipment_id)
);

CREATE TABLE PROCESS_STATUS (
  order_id    VARCHAR(36) NOT NULL,
  product_id  VARCHAR(36) NOT NULL,
  status      ENUM('WAIT','START','PAUSE','DONE') NOT NULL DEFAULT 'WAIT',
  start_ts    DATETIME NULL,
  end_ts      DATETIME NULL,
  CONSTRAINT PK_PROCESS_STATUS PRIMARY KEY (order_id, product_id)
);

CREATE TABLE PRODUCTION_LOG (
  log_id          BIGINT NOT NULL AUTO_INCREMENT,
  station_id      VARCHAR(36) NOT NULL,
  order_id        VARCHAR(36) NOT NULL,
  p_id            VARCHAR(36) NULL,
  event_type      ENUM('GOOD','DEFECT') NOT NULL DEFAULT 'GOOD',
  good_qty        INT NOT NULL DEFAULT 0,
  defect_qty      INT NOT NULL DEFAULT 0,
  defect_type     VARCHAR(50) NULL,
  defect_desc     TEXT NULL,
  defect_severity ENUM('LOW','MEDIUM','HIGH','CRITICAL') NULL,
  recorded_at     DATETIME NOT NULL,
  CONSTRAINT PK_PRODUCTION_LOG PRIMARY KEY (log_id)
);

CREATE TABLE LINE_KPI (
  kpi_id       BIGINT NOT NULL AUTO_INCREMENT,
  line_id      VARCHAR(36) NOT NULL,
  factory_id   INT NOT NULL,
  availability DECIMAL(5,2) NULL,
  performance  DECIMAL(5,2) NULL,
  quality      DECIMAL(5,2) NULL,
  oee          DECIMAL(5,2) NULL,
  created_at   DATETIME NULL,
  CONSTRAINT PK_LINE_KPI PRIMARY KEY (kpi_id)
);

CREATE TABLE EQUIPMENT_STATE_LOG (
  state_id     BIGINT NOT NULL AUTO_INCREMENT,
  station_id   VARCHAR(36) NOT NULL,
  equipment_id VARCHAR(36) NOT NULL,
  state        ENUM('RUN','IDLE','DOWN','MAINT') NOT NULL,
  start_ts     DATETIME NOT NULL,
  end_ts       DATETIME NULL,
  CONSTRAINT PK_EQUIP_STATE PRIMARY KEY (state_id)
);

CREATE TABLE EQUIPMENT_ERROR_LOG (
  error_id      BIGINT NOT NULL AUTO_INCREMENT,
  station_id    VARCHAR(36) NOT NULL,
  equipment_id  VARCHAR(36) NOT NULL,
  error_code    VARCHAR(50) NOT NULL,
  error_message TEXT NULL,
  severity      ENUM('LOW','MEDIUM','HIGH','CRITICAL') DEFAULT 'LOW',
  CONSTRAINT PK_EQUIP_ERROR PRIMARY KEY (error_id)
);

CREATE TABLE CAR_NAME (
  car_id     VARCHAR(36) NOT NULL,
  car_name   VARCHAR(100) NOT NULL,
  image_url  VARCHAR(255) NULL,
  factory_id INT NOT NULL,
  created_at DATETIME NULL,
  CONSTRAINT PK_CAR_NAME PRIMARY KEY (car_id),
  CONSTRAINT UQ_CAR_NAME UNIQUE (car_name)
);

-- 3) FK 추가 (기본 테이블 생성 이후)
ALTER TABLE STATION
  ADD CONSTRAINT FK_STATION_FACTORY
  FOREIGN KEY (factory_id) REFERENCES FACTORY(facId);

ALTER TABLE WORK_ORDER
  ADD CONSTRAINT FK_WO_PRODUCTMODEL
  FOREIGN KEY (product_id) REFERENCES PRODUCT_MODEL(product_id);

ALTER TABLE PRODUCT
  ADD CONSTRAINT FK_PRODUCT_ORDER     FOREIGN KEY (order_id)   REFERENCES WORK_ORDER(order_id),
  ADD CONSTRAINT FK_PRODUCT_TO_MODEL  FOREIGN KEY (product_id) REFERENCES PRODUCT_MODEL(product_id);

ALTER TABLE PRODUCT_ROUTING
  ADD CONSTRAINT FK_PR_PRODUCTMODEL
  FOREIGN KEY (product_id) REFERENCES PRODUCT_MODEL(product_id);

ALTER TABLE BOM
  ADD CONSTRAINT FK_BOM_PRODUCTMODEL FOREIGN KEY (product_id) REFERENCES PRODUCT_MODEL(product_id),
  ADD CONSTRAINT FK_BOM_ITEM         FOREIGN KEY (item_id)    REFERENCES ITEM(item_id);

ALTER TABLE STATION_EQUIPMENT
  ADD CONSTRAINT FK_SE_STATION FOREIGN KEY (station_id) REFERENCES STATION(station_id);

ALTER TABLE PROCESS_STATUS
  ADD CONSTRAINT FK_PS_ORDER        FOREIGN KEY (order_id)   REFERENCES WORK_ORDER(order_id),
  ADD CONSTRAINT FK_PS_PRODUCTMODEL FOREIGN KEY (product_id) REFERENCES PRODUCT_MODEL(product_id);

ALTER TABLE PRODUCTION_LOG
  ADD CONSTRAINT FK_PL_STATION FOREIGN KEY (station_id) REFERENCES STATION(station_id),
  ADD CONSTRAINT FK_PL_ORDER   FOREIGN KEY (order_id)   REFERENCES WORK_ORDER(order_id);

ALTER TABLE LINE_KPI
  ADD CONSTRAINT FK_LK_LINE FOREIGN KEY (line_id) REFERENCES STATION(line_id);

ALTER TABLE EQUIPMENT_STATE_LOG
  ADD CONSTRAINT FK_ESL_STATION FOREIGN KEY (station_id) REFERENCES STATION(station_id),
  ADD CONSTRAINT FK_ESL_EQUIP   FOREIGN KEY (station_id, equipment_id)
    REFERENCES STATION_EQUIPMENT(station_id, equipment_id);

ALTER TABLE EQUIPMENT_ERROR_LOG
  ADD CONSTRAINT FK_EE_STATION FOREIGN KEY (station_id) REFERENCES STATION(station_id),
  ADD CONSTRAINT FK_EE_EQUIP   FOREIGN KEY (station_id, equipment_id)
    REFERENCES STATION_EQUIPMENT(station_id, equipment_id);

ALTER TABLE CAR_NAME
  ADD CONSTRAINT FK_CARNAME_MODEL FOREIGN KEY (car_id) REFERENCES PRODUCT_MODEL(product_id);

-- 4) 인덱스
CREATE INDEX IX_WO_PLAN     ON WORK_ORDER(planned_s, planned_e);
CREATE INDEX IX_PR_SEQ      ON PRODUCT_ROUTING(product_id, process_seq);
CREATE INDEX IX_PS_STATUS   ON PROCESS_STATUS(status, start_ts);
CREATE INDEX IX_BOM_PRODUCT ON BOM(product_id);
CREATE INDEX IX_SE_STATION  ON STATION_EQUIPMENT(station_id);
CREATE INDEX IX_ST_LINEPROC ON STATION(line_id, process_type);

-- FK 재활성화
SET FOREIGN_KEY_CHECKS = 1;
